In [12]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
from sklearn.model_selection import train_test_split

# 데이터

In [18]:
data = np.array(range(1, 101)) 
pre_data = np.array(range(96, 106))  
timesteps = 5

def split_x(dataset, timesteps):
    tmp = []
    for i in range(len(dataset) - timesteps + 1):  
        subset = dataset[i : (i + timesteps)]
        tmp.append(subset)
    return np.array(tmp)

data = split_x(data, timesteps) 
pre_data = split_x(pre_data, timesteps)

print("split_dataset.shape :", data.shape)
print("split_pre_data.shape: ", pre_data.shape)

data_x = data[:, :-1] 
data_y = data[:, -1]

pre_data = pre_data[:, :-1] 
print("slicing_pre_data.shape : ", pre_data.shape)
print("slicing_pre_data:\n", pre_data)

print("data_x.shape: ", data_x.shape, "data_y.shape: ", data_y.shape)

x_train, x_test, y_train, y_test = train_test_split(data_x, data_y, train_size=0.7, random_state=3333) # default train_size = 0.75

print(x_train.shape, y_train.shape, x_test.shape, y_test.shape)

x_train = x_train.reshape(-1, 2, 2) # feature = 2로 변경
x_test = x_test.reshape(-1, 2, 2)
pre_data = pre_data.reshape(-1, 2, 2)

print(x_train.shape, y_train.shape, x_test.shape, y_test.shape)

split_dataset.shape : (96, 5)
split_pre_data.shape:  (6, 5)
slicing_pre_data.shape :  (6, 4)
slicing_pre_data:
 [[ 96  97  98  99]
 [ 97  98  99 100]
 [ 98  99 100 101]
 [ 99 100 101 102]
 [100 101 102 103]
 [101 102 103 104]]
slicing_x.shape:  (96, 4) slicing_y.shape:  (96,)
(67, 4) (67,) (29, 4) (29,)
(67, 2, 2) (67,) (29, 2, 2) (29,)


In [14]:
model = Sequential()                                                                     
model.add(LSTM(units = 64, input_shape=(2, 2), return_sequences=True, activation='relu')) 
model.add(LSTM(64, activation = 'relu'))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(64))
model.add(Dense(1))
model.summary() 

# LSTM을 두 개의 layer에서 사용할 때에는 return_sequences 파라미터를 지정해야한다. (default = False)


Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_7 (LSTM)               (None, 2, 64)             17152     
                                                                 
 lstm_8 (LSTM)               (None, 64)                33024     
                                                                 
 dense_9 (Dense)             (None, 64)                4160      
                                                                 
 dense_10 (Dense)            (None, 64)                4160      
                                                                 
 dense_11 (Dense)            (None, 1)                 65        
                                                                 
Total params: 58,561
Trainable params: 58,561
Non-trainable params: 0
_________________________________________________________________


# 컴파일, 훈련

In [15]:
model.compile(loss='mse', optimizer= 'adam')
model.fit(x_train, y_train, epochs=128, batch_size=3)

Epoch 1/128
23/23 [==============================] - 1s 3ms/step - loss: 1758.5417
Epoch 2/128
23/23 [==============================] - 0s 3ms/step - loss: 101.3116
Epoch 3/128
23/23 [==============================] - 0s 2ms/step - loss: 10.5633
Epoch 4/128
23/23 [==============================] - 0s 2ms/step - loss: 2.2360
Epoch 5/128
23/23 [==============================] - 0s 2ms/step - loss: 0.8445
Epoch 6/128
23/23 [==============================] - 0s 2ms/step - loss: 0.5469
Epoch 7/128
23/23 [==============================] - 0s 2ms/step - loss: 0.4725
Epoch 8/128
23/23 [==============================] - 0s 2ms/step - loss: 0.3419
Epoch 9/128
23/23 [==============================] - 0s 2ms/step - loss: 0.2646
Epoch 10/128
23/23 [==============================] - 0s 2ms/step - loss: 0.2682
Epoch 11/128
23/23 [==============================] - 0s 2ms/step - loss: 0.1894
Epoch 12/128
23/23 [==============================] - 0s 2ms/step - loss: 0.1444
Epoch 13/128
23/23 [===========

# 평가, 예측

In [16]:
loss = model.evaluate(x_test, y_test)
print(loss)

y_predict = np.array(pre_data)

result = model.predict(y_predict)

print('prediction result:\n', result) 

1/1 [==============================] - 0s 190ms/step - loss: 0.0505
0.05051634460687637
prediction result:
 [[100.03429 ]
 [101.05027 ]
 [102.06682 ]
 [103.08394 ]
 [104.10163 ]
 [105.119896]]
