In [32]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
from sklearn.model_selection import train_test_split

# 데이터

In [33]:
data = np.array(range(1, 101)) 
pre_data = np.array(range(96, 106))  
timesteps = 5

def split_x(dataset, timesteps):
    tmp = []
    for i in range(len(dataset) - timesteps + 1):  
        subset = dataset[i : (i + timesteps)]
        tmp.append(subset)
    return np.array(tmp)

data = split_x(data, timesteps) 
pre_data = split_x(pre_data, timesteps)

print("dataset.shape :", data.shape)
print("pre_data.shape: ", pre_data.shape)

x = data[:, :-1] 
y = data[:, -1]

pre_data = pre_data[:, :-1] 
print("slicing_pre_data.shape : ", pre_data.shape)
print("slicing_pre_data:\n", pre_data)

print("x.shape: ", x.shape, "y.shape: ", y.shape)

x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.7, random_state=3333) # default train_size = 0.75

print(x_train.shape, y_train.shape, x_test.shape, y_test.shape)

# x_train = x_train.reshape(-1, 4, 1)
# x_test = x_test.reshape(-1, 4, 1)
# pre_data = pre_data.reshape(-1, 4, 1)

dataset.shape : (96, 5)
pre_data.shape:  (6, 5)
slicing_pre_data.shape :  (6, 4)
slicing_pre_data:
 [[ 96  97  98  99]
 [ 97  98  99 100]
 [ 98  99 100 101]
 [ 99 100 101 102]
 [100 101 102 103]
 [101 102 103 104]]
x.shape:  (96, 4) y.shape:  (96,)
(67, 4) (67,) (29, 4) (29,)


In [34]:
model = Sequential()                                                                     
model.add(Dense(units = 64, input_shape=(4,), activation='relu')) 
model.add(Dense(64, activation = 'relu'))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(64))
model.add(Dense(1))
model.summary() 

# LSTM을 두 개의 layer에서 사용할 때에는 return_sequences 파라미터를 지정해야한다. (default = False)


Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_20 (Dense)            (None, 64)                320       
                                                                 
 dense_21 (Dense)            (None, 64)                4160      
                                                                 
 dense_22 (Dense)            (None, 64)                4160      
                                                                 
 dense_23 (Dense)            (None, 64)                4160      
                                                                 
 dense_24 (Dense)            (None, 1)                 65        
                                                                 
Total params: 12,865
Trainable params: 12,865
Non-trainable params: 0
_________________________________________________________________


# 컴파일, 훈련

In [47]:
model.compile(loss='mse', optimizer= 'adam')
model.fit(x_train, y_train, epochs=128, batch_size=3)

Epoch 1/128
23/23 [==============================] - 0s 1ms/step - loss: 4.1150
Epoch 2/128
23/23 [==============================] - 0s 954us/step - loss: 1.6891
Epoch 3/128
23/23 [==============================] - 0s 999us/step - loss: 0.9703
Epoch 4/128
23/23 [==============================] - 0s 956us/step - loss: 0.1170
Epoch 5/128
23/23 [==============================] - 0s 1ms/step - loss: 0.0032
Epoch 6/128
23/23 [==============================] - 0s 1ms/step - loss: 1.4019e-04
Epoch 7/128
23/23 [==============================] - 0s 953us/step - loss: 4.9061e-05
Epoch 8/128
23/23 [==============================] - 0s 1ms/step - loss: 6.2766e-05
Epoch 9/128
23/23 [==============================] - 0s 1000us/step - loss: 6.1052e-05
Epoch 10/128
23/23 [==============================] - 0s 1000us/step - loss: 3.2349e-05
Epoch 11/128
23/23 [==============================] - 0s 955us/step - loss: 6.0650e-05
Epoch 12/128
23/23 [==============================] - 0s 1ms/step - loss: 3.19

# 평가, 예측

In [48]:
loss = model.evaluate(x_test, y_test)
print("loss: ", loss)

y_predict = np.array(pre_data)

result = model.predict(y_predict)

print('prediction result:\n', result) 

1/1 [==============================] - 0s 63ms/step - loss: 1.3952e-04
loss:  0.0001395218714606017
prediction result:
 [[100.0171 ]
 [101.01726]
 [102.01741]
 [103.01757]
 [104.01772]
 [105.01788]]
