In [16]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Conv2D, Flatten
from sklearn.model_selection import train_test_split

# 데이터

In [26]:
data = np.array(range(1, 101)) 
pre_data = np.array(range(96, 106))  # [ 96  97  98  99 100 101 102 103 104 105]
print("data.shape :", data.shape)
print("pre_data.shape: ", pre_data.shape)

timesteps = 5
def split_x(dataset, timesteps):
    tmp = []
    for i in range(len(dataset) - timesteps + 1):  
        subset = dataset[i : (i + timesteps)]
        tmp.append(subset)
    return np.array(tmp)

split_data = split_x(data, timesteps) 
split_pre_data = split_x(pre_data, timesteps)
print("split_data.shape :", split_data.shape)
print("split_pre_data.shape: ", split_pre_data.shape)

# ------------------- slicing --------------------- #
data_x = split_data[:, :-1] # 마지막 열만 제거
data_y = split_data[:, -1] # 마지막 열만 추출
print("data_x.shape: ", data_x.shape, "data_y.shape: ", data_y.shape)
# print(data_x)
# print(data_y)

pre_data = split_pre_data[:, :-1] # 마지막 열만 제거
print("slicing_pre_data.shape : ", pre_data.shape)
print("slicing_pre_data:\n", pre_data)

x_train, x_test, y_train, y_test = train_test_split(data_x, data_y, train_size=0.7, random_state=3333) # default train_size = 0.75

print(x_train.shape, y_train.shape, x_test.shape, y_test.shape)

x_train = x_train.reshape(-1, 4, 1, 1)
x_test = x_test.reshape(-1, 4, 1, 1)
pre_data = pre_data.reshape(-1, 4, 1, 1)

print(x_train.shape, y_train.shape, x_test.shape, y_test.shape)

data.shape : (100,)
pre_data.shape:  (10,)
split_data.shape : (96, 5)
split_pre_data.shape:  (6, 5)
data_x.shape:  (96, 4) data_y.shape:  (96,)
slicing_pre_data.shape :  (6, 4)
slicing_pre_data:
 [[ 96  97  98  99]
 [ 97  98  99 100]
 [ 98  99 100 101]
 [ 99 100 101 102]
 [100 101 102 103]
 [101 102 103 104]]
(67, 4) (67,) (29, 4) (29,)
(67, 4, 1, 1) (67,) (29, 4, 1, 1) (29,)


In [18]:
model = Sequential()                                                                     
model.add(Conv2D(filters = 64, kernel_size= (2, 1), input_shape=(4, 1, 1), activation='relu')) 
model.add(Conv2D(filters = 64, kernel_size= (2, 1), activation = 'relu'))
model.add(Flatten())
model.add(Dense(64, activation = 'relu'))
model.add(Dense(64))
model.add(Dense(1))
model.summary() 

# LSTM을 두 개의 layer에서 사용할 때에는 return_sequences 파라미터를 지정해야한다. (default = False)


Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_6 (Conv2D)           (None, 3, 1, 64)          192       
                                                                 
 conv2d_7 (Conv2D)           (None, 2, 1, 64)          8256      
                                                                 
 flatten_3 (Flatten)         (None, 128)               0         
                                                                 
 dense_9 (Dense)             (None, 64)                8256      
                                                                 
 dense_10 (Dense)            (None, 64)                4160      
                                                                 
 dense_11 (Dense)            (None, 1)                 65        
                                                                 
Total params: 20,929
Trainable params: 20,929
Non-trai

# 컴파일, 훈련

In [19]:
model.compile(loss='mse', optimizer= 'adam')
model.fit(x_train, y_train, epochs=128, batch_size=3)

Epoch 1/128
23/23 [==============================] - 0s 1ms/step - loss: 1212.5804
Epoch 2/128
23/23 [==============================] - 0s 2ms/step - loss: 57.0994
Epoch 3/128
23/23 [==============================] - 0s 1ms/step - loss: 5.2307
Epoch 4/128
23/23 [==============================] - 0s 2ms/step - loss: 1.4561
Epoch 5/128
23/23 [==============================] - 0s 2ms/step - loss: 0.9502
Epoch 6/128
23/23 [==============================] - 0s 1ms/step - loss: 0.9249
Epoch 7/128
23/23 [==============================] - 0s 2ms/step - loss: 0.8543
Epoch 8/128
23/23 [==============================] - 0s 1ms/step - loss: 0.8070
Epoch 9/128
23/23 [==============================] - 0s 2ms/step - loss: 0.7774
Epoch 10/128
23/23 [==============================] - 0s 2ms/step - loss: 0.7689
Epoch 11/128
23/23 [==============================] - 0s 1ms/step - loss: 0.7353
Epoch 12/128
23/23 [==============================] - 0s 2ms/step - loss: 0.7409
Epoch 13/128
23/23 [=============

# 평가, 예측

In [20]:
loss = model.evaluate(x_test, y_test)
print(loss)

result = model.predict(pre_data)

print('prediction result:\n', result) 

1/1 [==============================] - 0s 106ms/step - loss: 0.0017
0.0017053293995559216
prediction result:
 [[100.08039 ]
 [101.08259 ]
 [102.08538 ]
 [103.088264]
 [104.09116 ]
 [105.09406 ]]
