In [20]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM

# 데이터

In [21]:
dataset = np.array(range(1, 101)) 
pre_data = np.array(range(96, 106))  
timesteps = 5

def split_x(dataset, timesteps):
    tmp = []
    for i in range(len(dataset) - timesteps + 1):
        subset = dataset[i : (i + timesteps)]
        tmp.append(subset)
    return np.array(tmp)

dataset = split_x(dataset, timesteps) 
pre_data = split_x(pre_data, timesteps)

print("dataset.shape :", dataset.shape)
print("pre_data.shape: ", pre_data.shape)

x = dataset[:, :-1] 
y = dataset[:, -1]

pre_data = pre_data[:, :-1] 
print("pre_data : ", pre_data)
print("pre_data.shape : ", pre_data.shape)

print("x.shape: ", x.shape, "y.shape: ", y.shape)

x = x.reshape(-1, 4, 1)


dataset.shape : (96, 5)
pre_data.shape:  (6, 5)
pre_data :  [[ 96  97  98  99]
 [ 97  98  99 100]
 [ 98  99 100 101]
 [ 99 100 101 102]
 [100 101 102 103]
 [101 102 103 104]]
pre_data.shape :  (6, 4)
x.shape:  (96, 4) y.shape:  (96,)


In [22]:
model = Sequential()                                                                      # (None, 3, 1)
model.add(LSTM(units = 64, input_shape=(4, 1), return_sequences=True, activation='relu')) # model.add(SimpleRNN(units = 64, input_length = 3, input_dim = 1)) # model.add(SimpleRNN(units = 64, input_shape=(3, 1)))
model.add(LSTM(64, activation = 'relu'))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(64))
model.add(Dense(64))
model.add(Dense(16))
model.add(Dense(1))
model.summary() 

# LSTM을 두 개의 layer에서 사용할 때에는 return_sequences 파라미터를 지정해야한다. (default = False)


Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_4 (LSTM)               (None, 4, 64)             16896     
                                                                 
 lstm_5 (LSTM)               (None, 64)                33024     
                                                                 
 dense_11 (Dense)            (None, 64)                4160      
                                                                 
 dense_12 (Dense)            (None, 64)                4160      
                                                                 
 dense_13 (Dense)            (None, 64)                4160      
                                                                 
 dense_14 (Dense)            (None, 16)                1040      
                                                                 
 dense_15 (Dense)            (None, 1)                

# 컴파일, 훈련

In [23]:
model.compile(loss='mse', optimizer= 'adam')
model.fit(x, y, epochs=512)

Epoch 1/512
3/3 [==============================] - 1s 19ms/step - loss: 3361.5359
Epoch 2/512
3/3 [==============================] - 0s 20ms/step - loss: 2425.7478
Epoch 3/512
3/3 [==============================] - 0s 18ms/step - loss: 991.6272
Epoch 4/512
3/3 [==============================] - 0s 20ms/step - loss: 371.5971
Epoch 5/512
3/3 [==============================] - 0s 19ms/step - loss: 377.3098
Epoch 6/512
3/3 [==============================] - 0s 20ms/step - loss: 64.4115
Epoch 7/512
3/3 [==============================] - 0s 17ms/step - loss: 185.2531
Epoch 8/512
3/3 [==============================] - 0s 17ms/step - loss: 153.8384
Epoch 9/512
3/3 [==============================] - 0s 20ms/step - loss: 21.2386
Epoch 10/512
3/3 [==============================] - 0s 19ms/step - loss: 50.8242
Epoch 11/512
3/3 [==============================] - 0s 18ms/step - loss: 37.5760
Epoch 12/512
3/3 [==============================] - 0s 17ms/step - loss: 4.3546
Epoch 13/512
3/3 [===========

# 평가, 예측

In [24]:
loss = model.evaluate(x, y)
print(loss)

y_predict = np.array(pre_data)

result = model.predict(y_predict)

print('prediction result:\n', result) 

3/3 [==============================] - 0s 7ms/step - loss: 1.1461e-04
0.00011461423855507746
prediction result:
 [[100.0153 ]
 [101.02055]
 [102.02618]
 [103.03217]
 [104.0385 ]
 [105.04514]]
