In [25]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM

# 데이터

In [26]:
dataset = np.array(range(1, 101)) 
pre_data = np.array(range(96, 106))  
timesteps = 5

def split_x(dataset, timesteps):
    tmp = []
    for i in range(len(dataset) - timesteps + 1):
        subset = dataset[i : (i + timesteps)]
        tmp.append(subset)
    return np.array(tmp)

dataset = split_x(dataset, timesteps) 
pre_data = split_x(pre_data, timesteps)

print("dataset.shape :", dataset.shape)
print("pre_data.shape: ", pre_data.shape)

x = dataset[:, :-1] 
y = dataset[:, -1]

pre_data = pre_data[:, :-1] 
print("pre_data : ", pre_data)
print("pre_data.shape : ", pre_data.shape)

print("x.shape: ", x.shape, "y.shape: ", y.shape)

x = x.reshape(-1, 4, 1)


dataset.shape : (96, 5)
pre_data.shape:  (6, 5)
pre_data :  [[ 96  97  98  99]
 [ 97  98  99 100]
 [ 98  99 100 101]
 [ 99 100 101 102]
 [100 101 102 103]
 [101 102 103 104]]
pre_data.shape :  (6, 4)
x.shape:  (96, 4) y.shape:  (96,)


In [27]:
model = Sequential()                                                                      # (None, 3, 1)
model.add(LSTM(units = 64, input_shape=(4, 1), return_sequences=True, activation='relu')) # model.add(SimpleRNN(units = 64, input_length = 3, input_dim = 1)) # model.add(SimpleRNN(units = 64, input_shape=(3, 1)))
model.add(LSTM(64, activation = 'relu'))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(64))
model.add(Dense(16))
model.add(Dense(1))
model.summary() 

# LSTM을 두 개의 layer에서 사용할 때에는 return_sequences 파라미터를 지정해야한다. (default = False)


Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_6 (LSTM)               (None, 4, 64)             16896     
                                                                 
 lstm_7 (LSTM)               (None, 64)                33024     
                                                                 
 dense_16 (Dense)            (None, 64)                4160      
                                                                 
 dense_17 (Dense)            (None, 64)                4160      
                                                                 
 dense_18 (Dense)            (None, 16)                1040      
                                                                 
 dense_19 (Dense)            (None, 1)                 17        
                                                                 
Total params: 59,297
Trainable params: 59,297
Non-trai

# 컴파일, 훈련

In [28]:
model.compile(loss='mse', optimizer= 'adam')
model.fit(x, y, epochs=256)

Epoch 1/256
3/3 [==============================] - 1s 18ms/step - loss: 3160.5955
Epoch 2/256
3/3 [==============================] - 0s 21ms/step - loss: 2500.2612
Epoch 3/256
3/3 [==============================] - 0s 20ms/step - loss: 1609.0464
Epoch 4/256
3/3 [==============================] - 0s 20ms/step - loss: 599.6119
Epoch 5/256
3/3 [==============================] - 0s 18ms/step - loss: 110.0763
Epoch 6/256
3/3 [==============================] - 0s 19ms/step - loss: 400.2561
Epoch 7/256
3/3 [==============================] - 0s 18ms/step - loss: 107.3810
Epoch 8/256
3/3 [==============================] - 0s 17ms/step - loss: 24.1393
Epoch 9/256
3/3 [==============================] - 0s 20ms/step - loss: 90.7747
Epoch 10/256
3/3 [==============================] - 0s 17ms/step - loss: 89.1728
Epoch 11/256
3/3 [==============================] - 0s 18ms/step - loss: 27.7765
Epoch 12/256
3/3 [==============================] - 0s 17ms/step - loss: 13.4733
Epoch 13/256
3/3 [=========

# 평가, 예측

In [29]:
loss = model.evaluate(x, y)
print(loss)

y_predict = np.array(pre_data)

result = model.predict(y_predict)

print('prediction result:\n', result) 

3/3 [==============================] - 0s 8ms/step - loss: 6.2641e-04
0.0006264127441681921
prediction result:
 [[100.03777 ]
 [101.04269 ]
 [102.0479  ]
 [103.053375]
 [104.059105]
 [105.06509 ]]
