In [16]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
from sklearn.model_selection import train_test_split

# 데이터

In [17]:
data = np.array(range(1, 101)) 
pre_data = np.array(range(96, 106))  
timesteps = 5

def split_x(dataset, timesteps):
    tmp = []
    for i in range(len(dataset) - timesteps + 1):  
        subset = dataset[i : (i + timesteps)]
        tmp.append(subset)
    return np.array(tmp)

data = split_x(data, timesteps) 
pre_data = split_x(pre_data, timesteps)

print("dataset.shape :", data.shape)
print("pre_data.shape: ", pre_data.shape)

data_x = data[:, :-1] 
data_y = data[:, -1]

pre_data = pre_data[:, :-1]
print("slicing_pre_data.shape : ", pre_data.shape)
print("slicing_pre_data:\n", pre_data)

print("data_x.shape: ", data_x.shape, "data_y.shape: ", data_y.shape)

x_train, x_test, y_train, y_test = train_test_split(data_x, data_y, train_size=0.7, random_state=3333) # default train_size = 0.75

print(x_train.shape, y_train.shape, x_test.shape, y_test.shape)

dataset.shape : (96, 5)
pre_data.shape:  (6, 5)
slicing_pre_data.shape :  (6, 4)
slicing_pre_data:
 [[ 96  97  98  99]
 [ 97  98  99 100]
 [ 98  99 100 101]
 [ 99 100 101 102]
 [100 101 102 103]
 [101 102 103 104]]
data_x.shape:  (96, 4) data_y.shape:  (96,)
(67, 4) (67,) (29, 4) (29,)


In [18]:
model = Sequential()                                                                     
model.add(Dense(units = 64, input_shape=(4,), activation='relu')) 
model.add(Dense(64, activation = 'relu'))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(64))
model.add(Dense(1))
model.summary() 

# LSTM을 두 개의 layer에서 사용할 때에는 return_sequences 파라미터를 지정해야한다. (default = False)


Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_15 (Dense)            (None, 64)                320       
                                                                 
 dense_16 (Dense)            (None, 64)                4160      
                                                                 
 dense_17 (Dense)            (None, 64)                4160      
                                                                 
 dense_18 (Dense)            (None, 64)                4160      
                                                                 
 dense_19 (Dense)            (None, 1)                 65        
                                                                 
Total params: 12,865
Trainable params: 12,865
Non-trainable params: 0
_________________________________________________________________


# 컴파일, 훈련

In [19]:
model.compile(loss='mse', optimizer= 'adam')
model.fit(x_train, y_train, epochs=128, batch_size=3)

Epoch 1/128
23/23 [==============================] - 0s 1000us/step - loss: 322.6212
Epoch 2/128
23/23 [==============================] - 0s 1ms/step - loss: 29.3466
Epoch 3/128
23/23 [==============================] - 0s 1ms/step - loss: 3.0213
Epoch 4/128
23/23 [==============================] - 0s 1ms/step - loss: 0.9913
Epoch 5/128
23/23 [==============================] - 0s 1ms/step - loss: 0.8583
Epoch 6/128
23/23 [==============================] - 0s 954us/step - loss: 0.8092
Epoch 7/128
23/23 [==============================] - 0s 1ms/step - loss: 0.8380
Epoch 8/128
23/23 [==============================] - 0s 1ms/step - loss: 0.7386
Epoch 9/128
23/23 [==============================] - 0s 955us/step - loss: 0.7184
Epoch 10/128
23/23 [==============================] - 0s 1ms/step - loss: 0.7457
Epoch 11/128
23/23 [==============================] - 0s 1ms/step - loss: 0.5452
Epoch 12/128
23/23 [==============================] - 0s 954us/step - loss: 0.5115
Epoch 13/128
23/23 [=====

# 평가, 예측

In [20]:
loss = model.evaluate(x_test, y_test)
print("loss: ", loss)

y_predict = np.array(pre_data)

result = model.predict(y_predict)

print('prediction result:\n', result)

1/1 [==============================] - 0s 66ms/step - loss: 0.0147
loss:  0.01471236627548933
prediction result:
 [[100.20026 ]
 [101.20225 ]
 [102.204285]
 [103.206276]
 [104.20829 ]
 [105.21028 ]]
