In [20]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Conv2D, Flatten
from sklearn.model_selection import train_test_split

# 데이터

In [21]:
data = np.array(range(1, 101)) 
pre_data = np.array(range(96, 106))  
timesteps = 5

def split_x(dataset, timesteps):
    tmp = []
    for i in range(len(dataset) - timesteps + 1):  
        subset = dataset[i : (i + timesteps)]
        tmp.append(subset)
    return np.array(tmp)

data = split_x(data, timesteps) 
pre_data = split_x(pre_data, timesteps)

print("split_dataset.shape :", data.shape)
print("split_pre_data.shape: ", pre_data.shape)

data_x = data[:, :-1] 
data_y = data[:, -1]

pre_data = pre_data[:, :-1] 
print("slicing_pre_data.shape : ", pre_data.shape)
print("slicing_pre_data:\n", pre_data)

print("data_x.shape: ", data_x.shape, "data_y.shape: ", data_y.shape)

x_train, x_test, y_train, y_test = train_test_split(data_x, data_y, train_size=0.7, random_state=3333) # default train_size = 0.75

print(x_train.shape, y_train.shape, x_test.shape, y_test.shape)

x_train = x_train.reshape(-1, 4, 1, 1)
x_test = x_test.reshape(-1, 4, 1, 1)
pre_data = pre_data.reshape(-1, 4, 1, 1)

print(x_train.shape, y_train.shape, x_test.shape, y_test.shape)

split_dataset.shape : (96, 5)
split_pre_data.shape:  (6, 5)
slicing_pre_data.shape :  (6, 4)
slicing_pre_data:
 [[ 96  97  98  99]
 [ 97  98  99 100]
 [ 98  99 100 101]
 [ 99 100 101 102]
 [100 101 102 103]
 [101 102 103 104]]
data_x.shape:  (96, 4) data_y.shape:  (96,)
(67, 4) (67,) (29, 4) (29,)
(67, 4, 1, 1) (67,) (29, 4, 1, 1) (29,)


In [22]:
model = Sequential()                                                                     
model.add(Conv2D(filters = 64, kernel_size= (2, 1), input_shape=(4, 1, 1), activation='relu')) 
model.add(Conv2D(filters = 64, kernel_size= (2, 1), activation = 'relu'))
model.add(Flatten())
model.add(Dense(64, activation = 'relu'))
model.add(Dense(64))
model.add(Dense(1))
model.summary() 

# LSTM을 두 개의 layer에서 사용할 때에는 return_sequences 파라미터를 지정해야한다. (default = False)


Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_7 (Conv2D)           (None, 3, 1, 64)          192       
                                                                 
 conv2d_8 (Conv2D)           (None, 2, 1, 64)          8256      
                                                                 
 flatten_3 (Flatten)         (None, 128)               0         
                                                                 
 dense_9 (Dense)             (None, 64)                8256      
                                                                 
 dense_10 (Dense)            (None, 64)                4160      
                                                                 
 dense_11 (Dense)            (None, 1)                 65        
                                                                 
Total params: 20,929
Trainable params: 20,929
Non-trai

# 컴파일, 훈련

In [23]:
model.compile(loss='mse', optimizer= 'adam')
model.fit(x_train, y_train, epochs=128, batch_size=3)

Epoch 1/128
23/23 [==============================] - 0s 6ms/step - loss: 1054.2891
Epoch 2/128
23/23 [==============================] - 0s 5ms/step - loss: 48.2144
Epoch 3/128
23/23 [==============================] - 0s 4ms/step - loss: 7.2127
Epoch 4/128
23/23 [==============================] - 0s 4ms/step - loss: 1.1647
Epoch 5/128
23/23 [==============================] - 0s 4ms/step - loss: 1.1350
Epoch 6/128
23/23 [==============================] - 0s 4ms/step - loss: 0.9090
Epoch 7/128
23/23 [==============================] - 0s 4ms/step - loss: 0.7469
Epoch 8/128
23/23 [==============================] - 0s 4ms/step - loss: 0.7074
Epoch 9/128
23/23 [==============================] - 0s 4ms/step - loss: 0.7107
Epoch 10/128
23/23 [==============================] - 0s 4ms/step - loss: 0.6080
Epoch 11/128
23/23 [==============================] - 0s 4ms/step - loss: 0.6003
Epoch 12/128
23/23 [==============================] - 0s 4ms/step - loss: 0.7653
Epoch 13/128
23/23 [=============

# 평가, 예측

In [24]:
loss = model.evaluate(x_test, y_test)
print(loss)

result = model.predict(pre_data)

print('prediction result:\n', result) 

1/1 [==============================] - 0s 79ms/step - loss: 7.8888e-05
7.888847903814167e-05
prediction result:
 [[100.004585]
 [101.004616]
 [102.00465 ]
 [103.00469 ]
 [104.00472 ]
 [105.00476 ]]
