In [78]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
from sklearn.model_selection import train_test_split

# 데이터

In [79]:
dataset = np.array(range(1, 101)) 
pre_data = np.array(range(96, 106))  
timesteps = 5

def split_x(dataset, timesteps):
    tmp = []
    for i in range(len(dataset) - timesteps + 1):
        subset = dataset[i : (i + timesteps)]
        tmp.append(subset)
    return np.array(tmp)

dataset = split_x(dataset, timesteps) 
pre_data = split_x(pre_data, timesteps)

print("dataset.shape :", dataset.shape)
print("pre_data.shape: ", pre_data.shape)

x = dataset[:, :-1] 
y = dataset[:, -1]

pre_data = pre_data[:, :-1] 
print("slicing_pre_data.shape : ", pre_data.shape)
print("slicing_pre_data:\n", pre_data)

print("x.shape: ", x.shape, "y.shape: ", y.shape)

x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.7, random_state=3333) # default train_size = 0.75

print(x_train.shape, y_train.shape, x_test.shape, y_test.shape)

x_train = x_train.reshape(-1, 4, 1)
x_test = x_test.reshape(-1, 4, 1)


dataset.shape : (96, 5)
pre_data.shape:  (6, 5)
slicing_pre_data.shape :  (6, 4)
slicing_pre_data:
 [[ 96  97  98  99]
 [ 97  98  99 100]
 [ 98  99 100 101]
 [ 99 100 101 102]
 [100 101 102 103]
 [101 102 103 104]]
x.shape:  (96, 4) y.shape:  (96,)
(67, 4) (67,) (29, 4) (29,)


In [80]:
model = Sequential()                                                                      # (None, 3, 1)
model.add(LSTM(units = 64, input_shape=(4, 1), return_sequences=True, activation='relu')) # model.add(SimpleRNN(units = 64, input_length = 3, input_dim = 1)) # model.add(SimpleRNN(units = 64, input_shape=(3, 1)))
model.add(LSTM(64, activation = 'relu'))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(64))
model.add(Dense(16))
model.add(Dense(1))
model.summary() 

# LSTM을 두 개의 layer에서 사용할 때에는 return_sequences 파라미터를 지정해야한다. (default = False)


Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_20 (LSTM)              (None, 4, 64)             16896     
                                                                 
 lstm_21 (LSTM)              (None, 64)                33024     
                                                                 
 dense_44 (Dense)            (None, 64)                4160      
                                                                 
 dense_45 (Dense)            (None, 64)                4160      
                                                                 
 dense_46 (Dense)            (None, 16)                1040      
                                                                 
 dense_47 (Dense)            (None, 1)                 17        
                                                                 
Total params: 59,297
Trainable params: 59,297
Non-tra

# 컴파일, 훈련

In [81]:
model.compile(loss='mse', optimizer= 'adam')
model.fit(x_train, y_train, epochs=128)

Epoch 1/128
3/3 [==============================] - 1s 40ms/step - loss: 3585.3940
Epoch 2/128
3/3 [==============================] - 0s 40ms/step - loss: 2950.9246
Epoch 3/128
3/3 [==============================] - 0s 34ms/step - loss: 2370.4790
Epoch 4/128
3/3 [==============================] - 0s 37ms/step - loss: 1569.1599
Epoch 5/128
3/3 [==============================] - 0s 32ms/step - loss: 639.1449
Epoch 6/128
3/3 [==============================] - 0s 31ms/step - loss: 77.6012
Epoch 7/128
3/3 [==============================] - 0s 31ms/step - loss: 357.1908
Epoch 8/128
3/3 [==============================] - 0s 40ms/step - loss: 181.0389
Epoch 9/128
3/3 [==============================] - 0s 36ms/step - loss: 26.5415
Epoch 10/128
3/3 [==============================] - 0s 36ms/step - loss: 40.7255
Epoch 11/128
3/3 [==============================] - 0s 39ms/step - loss: 41.2380
Epoch 12/128
3/3 [==============================] - 0s 35ms/step - loss: 8.3254
Epoch 13/128
3/3 [=========

# 평가, 예측

In [82]:
loss = model.evaluate(x_test, y_test)
print(loss)

y_predict = np.array(pre_data)

result = model.predict(y_predict)

print('prediction result:\n', result) 

1/1 [==============================] - 0s 229ms/step - loss: 0.0274
0.027419257909059525
prediction result:
 [[100.03801 ]
 [101.04325 ]
 [102.048676]
 [103.05434 ]
 [104.060196]
 [105.06623 ]]
