In [6]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
from sklearn.model_selection import train_test_split

# 데이터

In [7]:
data = np.array(range(1, 101)) 
pre_data = np.array(range(96, 106))  
timesteps = 5

def split_x(dataset, timesteps):
    tmp = []
    for i in range(len(dataset) - timesteps + 1):  
        subset = dataset[i : (i + timesteps)]
        tmp.append(subset)
    return np.array(tmp)

data = split_x(data, timesteps) 
pre_data = split_x(pre_data, timesteps)

print("dataset.shape :", data.shape)
print("pre_data.shape: ", pre_data.shape)

x = data[:, :-1] 
y = data[:, -1]

pre_data = pre_data[:, :-1] 
print("slicing_pre_data.shape : ", pre_data.shape)
print("slicing_pre_data:\n", pre_data)

print("x.shape: ", x.shape, "y.shape: ", y.shape)

x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.7, random_state=3333) # default train_size = 0.75

print(x_train.shape, y_train.shape, x_test.shape, y_test.shape)

# x_train = x_train.reshape(-1, 4, 1)
# x_test = x_test.reshape(-1, 4, 1)
# pre_data = pre_data.reshape(-1, 4, 1)

dataset.shape : (96, 5)
pre_data.shape:  (6, 5)
slicing_pre_data.shape :  (6, 4)
slicing_pre_data:
 [[ 96  97  98  99]
 [ 97  98  99 100]
 [ 98  99 100 101]
 [ 99 100 101 102]
 [100 101 102 103]
 [101 102 103 104]]
x.shape:  (96, 4) y.shape:  (96,)
(67, 4) (67,) (29, 4) (29,)


In [8]:
model = Sequential()                                                                     
model.add(LSTM(units = 64, input_shape=(4, 1), return_sequences=True, activation='relu')) 
model.add(LSTM(64, activation = 'relu'))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(64))
model.add(Dense(1))
model.summary() 

# LSTM을 두 개의 layer에서 사용할 때에는 return_sequences 파라미터를 지정해야한다. (default = False)


Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_2 (LSTM)               (None, 4, 64)             16896     
                                                                 
 lstm_3 (LSTM)               (None, 64)                33024     
                                                                 
 dense_3 (Dense)             (None, 64)                4160      
                                                                 
 dense_4 (Dense)             (None, 64)                4160      
                                                                 
 dense_5 (Dense)             (None, 1)                 65        
                                                                 
Total params: 58,305
Trainable params: 58,305
Non-trainable params: 0
_________________________________________________________________


# 컴파일, 훈련

In [9]:
model.compile(loss='mse', optimizer= 'adam')
model.fit(x_train, y_train, epochs=128, batch_size=3)

Epoch 1/128
23/23 [==============================] - 1s 4ms/step - loss: 1469.8639
Epoch 2/128
23/23 [==============================] - 0s 3ms/step - loss: 20.3456
Epoch 3/128
23/23 [==============================] - 0s 3ms/step - loss: 5.4580
Epoch 4/128
23/23 [==============================] - 0s 2ms/step - loss: 1.0262
Epoch 5/128
23/23 [==============================] - 0s 3ms/step - loss: 0.3863
Epoch 6/128
23/23 [==============================] - 0s 3ms/step - loss: 0.2392
Epoch 7/128
23/23 [==============================] - 0s 3ms/step - loss: 0.1361
Epoch 8/128
23/23 [==============================] - 0s 3ms/step - loss: 0.1047
Epoch 9/128
23/23 [==============================] - 0s 3ms/step - loss: 0.0813
Epoch 10/128
23/23 [==============================] - 0s 3ms/step - loss: 0.0673
Epoch 11/128
23/23 [==============================] - 0s 3ms/step - loss: 0.0315
Epoch 12/128
23/23 [==============================] - 0s 3ms/step - loss: 0.0371
Epoch 13/128
23/23 [=============

# 평가, 예측

In [10]:
loss = model.evaluate(x_test, y_test)
print(loss)

result = model.predict(pre_data)

print('prediction result:\n', result) 

1/1 [==============================] - 0s 201ms/step - loss: 0.0343
0.03433776646852493
prediction result:
 [[100.4112  ]
 [101.42638 ]
 [102.44158 ]
 [103.456825]
 [104.47211 ]
 [105.4874  ]]
