In [1]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM

# 데이터

In [2]:
dataset = np.array(range(1, 11)) 
timesteps = 5

def split_x(dataset, timesteps):
    tmp = []
    for i in range(len(dataset) - timesteps + 1):
        subset = dataset[i : (i + timesteps)]
        tmp.append(subset)
    return np.array(tmp)

result = split_x(dataset, timesteps)
print(result)

x = result[:, :-1] 
y = result[:, -1]
print("x:\n", x, "\ny: ", y)
print("x.shape: ", x.shape, "y.shape: ", y.shape)

# x = x.reshape(6, 4, 1) #(N, timesteps, feature)

[[ 1  2  3  4  5]
 [ 2  3  4  5  6]
 [ 3  4  5  6  7]
 [ 4  5  6  7  8]
 [ 5  6  7  8  9]
 [ 6  7  8  9 10]]
x:
 [[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]] 
y:  [ 5  6  7  8  9 10]
x.shape:  (6, 4) y.shape:  (6,)


In [3]:
model = Sequential()                                                                      # (None, 3, 1)
model.add(LSTM(units = 64, input_shape=(4, 1), return_sequences=True, activation='relu')) # model.add(SimpleRNN(units = 64, input_length = 3, input_dim = 1)) # model.add(SimpleRNN(units = 64, input_shape=(3, 1)))
model.add(LSTM(64, activation = 'relu'))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(64))
model.add(Dense(64))
model.add(Dense(16))
model.add(Dense(1))
model.summary() 

# LSTM을 두 개의 layer에서 사용할 때에는 return_sequences 파라미터를 지정해야한다. (default = False)


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 4, 64)             16896     
                                                                 
 lstm_1 (LSTM)               (None, 64)                33024     
                                                                 
 dense (Dense)               (None, 64)                4160      
                                                                 
 dense_1 (Dense)             (None, 64)                4160      
                                                                 
 dense_2 (Dense)             (None, 64)                4160      
                                                                 
 dense_3 (Dense)             (None, 16)                1040      
                                                                 
 dense_4 (Dense)             (None, 1)                 1

# 컴파일, 훈련

In [4]:
model.compile(loss='mse', optimizer= 'adam')
model.fit(x, y, epochs=256)

Epoch 1/256
1/1 [==============================] - 2s 2s/step - loss: 59.0075
Epoch 2/256
1/1 [==============================] - 0s 29ms/step - loss: 57.6666
Epoch 3/256
1/1 [==============================] - 0s 33ms/step - loss: 56.2895
Epoch 4/256
1/1 [==============================] - 0s 31ms/step - loss: 54.7033
Epoch 5/256
1/1 [==============================] - 0s 35ms/step - loss: 52.8186
Epoch 6/256
1/1 [==============================] - 0s 34ms/step - loss: 50.5953
Epoch 7/256
1/1 [==============================] - 0s 31ms/step - loss: 47.9745
Epoch 8/256
1/1 [==============================] - 0s 30ms/step - loss: 44.8962
Epoch 9/256
1/1 [==============================] - 0s 32ms/step - loss: 41.3013
Epoch 10/256
1/1 [==============================] - 0s 29ms/step - loss: 37.1365
Epoch 11/256
1/1 [==============================] - 0s 36ms/step - loss: 32.3592
Epoch 12/256
1/1 [==============================] - 0s 35ms/step - loss: 26.9559
Epoch 13/256
1/1 [=====================

# 평가, 예측

In [5]:
loss = model.evaluate(x, y)
print(loss)

y_predict = np.array([[7, 8, 9, 10]])

result = model.predict(y_predict)

print('prediction result: ', result) 

1/1 [==============================] - 0s 240ms/step - loss: 2.2037e-04
0.0002203728654421866
prediction result:  [[10.931929]]
