In [64]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Bidirectional, Conv1D, GRU, Flatten
from sklearn.model_selection import train_test_split

# 데이터

In [65]:
data = np.array(range(1, 101)) 
pre_data = np.array(range(96, 106))  
timesteps = 5

def split_x(dataset, timesteps):
    tmp = []
    for i in range(len(dataset) - timesteps + 1):  
        subset = dataset[i : (i + timesteps)]
        tmp.append(subset)
    return np.array(tmp)

data = split_x(data, timesteps) 
pre_data = split_x(pre_data, timesteps)

print("dataset.shape :", data.shape)
print("pre_data.shape: ", pre_data.shape)

x = data[:, :-1] 
y = data[:, -1]

pre_data = pre_data[:, :-1] 
print("slicing_pre_data.shape : ", pre_data.shape)
print("slicing_pre_data:\n", pre_data)

print("x.shape: ", x.shape, "y.shape: ", y.shape)

x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.7, random_state=3333) # default train_size = 0.75

print(x_train.shape, y_train.shape, x_test.shape, y_test.shape)

# x_train = x_train.reshape(-1, 4, 1)
# x_test = x_test.reshape(-1, 4, 1)
# pre_data = pre_data.reshape(-1, 4, 1)

dataset.shape : (96, 5)
pre_data.shape:  (6, 5)
slicing_pre_data.shape :  (6, 4)
slicing_pre_data:
 [[ 96  97  98  99]
 [ 97  98  99 100]
 [ 98  99 100 101]
 [ 99 100 101 102]
 [100 101 102 103]
 [101 102 103 104]]
x.shape:  (96, 4) y.shape:  (96,)
(67, 4) (67,) (29, 4) (29,)


In [66]:
model = Sequential()                                                                     
model.add(Conv1D(filters=64, kernel_size=2, input_shape=(4, 1)))
# model.add(Bidirectional(LSTM(units=64, return_sequences=True, activation='relu')))
# model.add(GRU(units=64, activation = 'relu'))
model.add(Flatten())
model.add(Dense(units=64, activation = 'relu'))
model.add(Dense(64))
model.add(Dense(1))
model.summary() 
# LSTM을 두 개의 layer에서 사용할 때에는 return_sequences 파라미터를 지정해야한다. (default = False)

Model: "sequential_15"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d_12 (Conv1D)          (None, 3, 64)             192       
                                                                 
 flatten (Flatten)           (None, 192)               0         
                                                                 
 dense_27 (Dense)            (None, 64)                12352     
                                                                 
 dense_28 (Dense)            (None, 64)                4160      
                                                                 
 dense_29 (Dense)            (None, 1)                 65        
                                                                 
Total params: 16,769
Trainable params: 16,769
Non-trainable params: 0
_________________________________________________________________


# 컴파일, 훈련

In [67]:
model.compile(loss='mse', optimizer= 'adam')
model.fit(x_train, y_train, epochs=128, batch_size=3)

Epoch 1/128
23/23 [==============================] - 0s 1ms/step - loss: 254.3211
Epoch 2/128
23/23 [==============================] - 0s 1ms/step - loss: 12.2088
Epoch 3/128
23/23 [==============================] - 0s 1ms/step - loss: 2.8031
Epoch 4/128
23/23 [==============================] - 0s 1ms/step - loss: 1.3914
Epoch 5/128
23/23 [==============================] - 0s 1ms/step - loss: 1.2866
Epoch 6/128
23/23 [==============================] - 0s 1ms/step - loss: 1.2767
Epoch 7/128
23/23 [==============================] - 0s 1ms/step - loss: 1.2099
Epoch 8/128
23/23 [==============================] - 0s 3ms/step - loss: 1.1915
Epoch 9/128
23/23 [==============================] - 0s 1ms/step - loss: 1.2447
Epoch 10/128
23/23 [==============================] - 0s 1ms/step - loss: 1.1434
Epoch 11/128
23/23 [==============================] - 0s 954us/step - loss: 1.0574
Epoch 12/128
23/23 [==============================] - 0s 818us/step - loss: 1.0417
Epoch 13/128
23/23 [==========

# 평가, 예측

In [68]:
loss = model.evaluate(x_test, y_test)
print(loss)

result = model.predict(pre_data)

print('prediction result:\n', result) 

1/1 [==============================] - 0s 64ms/step - loss: 0.0937
0.09368707239627838
prediction result:
 [[ 99.62334 ]
 [100.621796]
 [101.62022 ]
 [102.61867 ]
 [103.61713 ]
 [104.61558 ]]
