In [45]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM

# 데이터

In [46]:
dataset = np.array(range(1, 101)) 
pre_data = np.array(range(96, 106))  

def split_x(dataset, timesteps):
    tmp = []
    for i in range(len(dataset) - timesteps + 1):
        subset = dataset[i : (i + timesteps)]
        tmp.append(subset)
    return np.array(tmp)

dataset = split_x(dataset, 5) 
pre_data = split_x(pre_data, 4)

print("dataset.shape :", dataset.shape)
print("pre_data.shape: ", pre_data.shape)

x = dataset[:, :-1] 
y = dataset[:, -1]

print("pre_data : ", pre_data)
print("pre_data.shape : ", pre_data.shape)

print("x.shape: ", x.shape, "y.shape: ", y.shape)

x = x.reshape(-1, 4, 1)


dataset.shape : (96, 5)
pre_data.shape:  (7, 4)
pre_data :  [[ 96  97  98  99]
 [ 97  98  99 100]
 [ 98  99 100 101]
 [ 99 100 101 102]
 [100 101 102 103]
 [101 102 103 104]
 [102 103 104 105]]
pre_data.shape :  (7, 4)
x.shape:  (96, 4) y.shape:  (96,)


In [47]:
model = Sequential()                                                                      # (None, 3, 1)
model.add(LSTM(units = 64, input_shape=(4, 1), return_sequences=True, activation='relu')) # model.add(SimpleRNN(units = 64, input_length = 3, input_dim = 1)) # model.add(SimpleRNN(units = 64, input_shape=(3, 1)))
model.add(LSTM(64, activation = 'relu'))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(64))
model.add(Dense(16))
model.add(Dense(1))
model.summary() 

# LSTM을 두 개의 layer에서 사용할 때에는 return_sequences 파라미터를 지정해야한다. (default = False)


Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_12 (LSTM)              (None, 4, 64)             16896     
                                                                 
 lstm_13 (LSTM)              (None, 64)                33024     
                                                                 
 dense_28 (Dense)            (None, 64)                4160      
                                                                 
 dense_29 (Dense)            (None, 64)                4160      
                                                                 
 dense_30 (Dense)            (None, 16)                1040      
                                                                 
 dense_31 (Dense)            (None, 1)                 17        
                                                                 
Total params: 59,297
Trainable params: 59,297
Non-trai

# 컴파일, 훈련

In [48]:
model.compile(loss='mse', optimizer= 'adam')
model.fit(x, y, epochs=256)

Epoch 1/256
3/3 [==============================] - 1s 19ms/step - loss: 3182.3240
Epoch 2/256
3/3 [==============================] - 0s 18ms/step - loss: 2548.0818
Epoch 3/256
3/3 [==============================] - 0s 18ms/step - loss: 1561.8691
Epoch 4/256
3/3 [==============================] - 0s 18ms/step - loss: 331.6217
Epoch 5/256
3/3 [==============================] - 0s 20ms/step - loss: 296.9690
Epoch 6/256
3/3 [==============================] - 0s 19ms/step - loss: 359.4781
Epoch 7/256
3/3 [==============================] - 0s 20ms/step - loss: 37.1812
Epoch 8/256
3/3 [==============================] - 0s 21ms/step - loss: 80.7096
Epoch 9/256
3/3 [==============================] - 0s 19ms/step - loss: 134.3741
Epoch 10/256
3/3 [==============================] - 0s 20ms/step - loss: 79.2242
Epoch 11/256
3/3 [==============================] - 0s 18ms/step - loss: 12.5540
Epoch 12/256
3/3 [==============================] - 0s 19ms/step - loss: 23.6657
Epoch 13/256
3/3 [=========

# 평가, 예측

In [49]:
loss = model.evaluate(x, y)
print(loss)

y_predict = np.array(pre_data)

result = model.predict(y_predict)

print('prediction result:\n', result) 

3/3 [==============================] - 0s 7ms/step - loss: 7.1425e-04
0.0007142468821257353
prediction result:
 [[100.05991 ]
 [101.07261 ]
 [102.08611 ]
 [103.10041 ]
 [104.115486]
 [105.131325]
 [106.14791 ]]
