In [57]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM

# 데이터

In [58]:
dataset = np.array(range(1, 101)) 
pre_data = np.array(range(96, 106))  
timesteps = 5

def split_x(dataset, timesteps):
    tmp = []
    for i in range(len(dataset) - timesteps + 1):
        subset = dataset[i : (i + timesteps)]
        tmp.append(subset)
    return np.array(tmp)

dataset = split_x(dataset, timesteps) 
pre_data = split_x(pre_data, timesteps)

print("dataset.shape :", dataset.shape)
print("pre_data.shape: ", pre_data.shape)

x = dataset[:, :-1] 
y = dataset[:, -1]

pre_data = pre_data[:, :-1] 
print("pre_data : ", pre_data)
print("pre_data.shape : ", pre_data.shape)

print("x.shape: ", x.shape, "y.shape: ", y.shape)

x = x.reshape(-1, 4, 1)


dataset.shape : (96, 5)
pre_data.shape:  (6, 5)
pre_data :  [[ 96  97  98  99]
 [ 97  98  99 100]
 [ 98  99 100 101]
 [ 99 100 101 102]
 [100 101 102 103]
 [101 102 103 104]]
pre_data.shape :  (6, 4)
x.shape:  (96, 4) y.shape:  (96,)


In [59]:
model = Sequential()                                                                      # (None, 3, 1)
model.add(LSTM(units = 64, input_shape=(4, 1), return_sequences=True, activation='relu')) # model.add(SimpleRNN(units = 64, input_length = 3, input_dim = 1)) # model.add(SimpleRNN(units = 64, input_shape=(3, 1)))
model.add(LSTM(64, activation = 'relu'))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(64))
model.add(Dense(16))
model.add(Dense(1))
model.summary() 

# LSTM을 두 개의 layer에서 사용할 때에는 return_sequences 파라미터를 지정해야한다. (default = False)


Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_16 (LSTM)              (None, 4, 64)             16896     
                                                                 
 lstm_17 (LSTM)              (None, 64)                33024     
                                                                 
 dense_36 (Dense)            (None, 64)                4160      
                                                                 
 dense_37 (Dense)            (None, 64)                4160      
                                                                 
 dense_38 (Dense)            (None, 16)                1040      
                                                                 
 dense_39 (Dense)            (None, 1)                 17        
                                                                 
Total params: 59,297
Trainable params: 59,297
Non-trai

# 컴파일, 훈련

In [60]:
model.compile(loss='mse', optimizer= 'adam')
model.fit(x, y, epochs=128)

Epoch 1/128
3/3 [==============================] - 1s 22ms/step - loss: 3498.5203
Epoch 2/128
3/3 [==============================] - 0s 20ms/step - loss: 2998.8508
Epoch 3/128
3/3 [==============================] - 0s 17ms/step - loss: 2054.3569
Epoch 4/128
3/3 [==============================] - 0s 19ms/step - loss: 647.6399
Epoch 5/128
3/3 [==============================] - 0s 20ms/step - loss: 246.0428
Epoch 6/128
3/3 [==============================] - 0s 17ms/step - loss: 401.2574
Epoch 7/128
3/3 [==============================] - 0s 17ms/step - loss: 36.1496
Epoch 8/128
3/3 [==============================] - 0s 17ms/step - loss: 112.7297
Epoch 9/128
3/3 [==============================] - 0s 17ms/step - loss: 119.9655
Epoch 10/128
3/3 [==============================] - 0s 16ms/step - loss: 25.8327
Epoch 11/128
3/3 [==============================] - 0s 16ms/step - loss: 32.6941
Epoch 12/128
3/3 [==============================] - 0s 17ms/step - loss: 27.3018
Epoch 13/128
3/3 [========

# 평가, 예측

In [62]:
loss = model.evaluate(x, y)
print(loss)

y_predict = np.array(pre_data)

result = model.predict(y_predict)

print('prediction result:\n', result) 

3/3 [==============================] - 0s 7ms/step - loss: 9.0540e-04
0.0009053995017893612
prediction result:
 [[100.02192 ]
 [101.02184 ]
 [102.02168 ]
 [103.02142 ]
 [104.021065]
 [105.02061 ]]
