In [103]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM

# 데이터

In [104]:
dataset = np.array(range(1, 11)) 
timesteps = 5

def split_x(dataset, timesteps):
    tmp = []
    for i in range(len(dataset) - timesteps + 1):
        subset = dataset[i : (i + timesteps)]
        tmp.append(subset)
    return np.array(tmp)

result = split_x(dataset, timesteps)
print(result)

x = result[:, :-1] 
y = result[:, -1]
print("x:\n", x, "\ny: ", y)
print(x.shape, y.shape)

x = x.reshape(6, 4, 1)

[[ 1  2  3  4  5]
 [ 2  3  4  5  6]
 [ 3  4  5  6  7]
 [ 4  5  6  7  8]
 [ 5  6  7  8  9]
 [ 6  7  8  9 10]]
x:
 [[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]] 
y:  [ 5  6  7  8  9 10]
(6, 4) (6,)


In [105]:
model = Sequential()                                                                      # (None, 3, 1)
model.add(LSTM(units = 64, input_shape=(4, 1), return_sequences=True, activation='relu')) # model.add(SimpleRNN(units = 64, input_length = 3, input_dim = 1)) # model.add(SimpleRNN(units = 64, input_shape=(3, 1)))
model.add(LSTM(64, activation = 'relu'))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(64))
model.add(Dense(64))
model.add(Dense(16))
model.add(Dense(1))
model.summary() 

# LSTM을 두 개의 layer에서 사용할 때에는 return_sequences 파라미터를 지정해야한다. (default = False)


Model: "sequential_15"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_30 (LSTM)              (None, 4, 64)             16896     
                                                                 
 lstm_31 (LSTM)              (None, 64)                33024     
                                                                 
 dense_55 (Dense)            (None, 64)                4160      
                                                                 
 dense_56 (Dense)            (None, 64)                4160      
                                                                 
 dense_57 (Dense)            (None, 64)                4160      
                                                                 
 dense_58 (Dense)            (None, 16)                1040      
                                                                 
 dense_59 (Dense)            (None, 1)               

# 컴파일, 훈련

In [106]:
model.compile(loss='mse', optimizer= 'adam')
model.fit(x, y, epochs=256)

Epoch 1/256
1/1 [==============================] - 2s 2s/step - loss: 59.9860
Epoch 2/256
1/1 [==============================] - 0s 46ms/step - loss: 58.2584
Epoch 3/256
1/1 [==============================] - 0s 39ms/step - loss: 56.6702
Epoch 4/256
1/1 [==============================] - 0s 38ms/step - loss: 54.9833
Epoch 5/256
1/1 [==============================] - 0s 37ms/step - loss: 53.0902
Epoch 6/256
1/1 [==============================] - 0s 30ms/step - loss: 50.9201
Epoch 7/256
1/1 [==============================] - 0s 33ms/step - loss: 48.4068
Epoch 8/256
1/1 [==============================] - 0s 28ms/step - loss: 45.4774
Epoch 9/256
1/1 [==============================] - 0s 32ms/step - loss: 42.0688
Epoch 10/256
1/1 [==============================] - 0s 34ms/step - loss: 38.1405
Epoch 11/256
1/1 [==============================] - 0s 30ms/step - loss: 33.6552
Epoch 12/256
1/1 [==============================] - 0s 31ms/step - loss: 28.5865
Epoch 13/256
1/1 [=====================

# 평가, 예측

In [107]:
loss = model.evaluate(x, y)
print(loss)

y_predict = np.array([[7, 8, 9, 10]]) #또는 .reshape(1, 3, 1)

result = model.predict(y_predict)

print('prediction result: ', result) 

1/1 [==============================] - 0s 322ms/step - loss: 1.1740e-05
1.1740361514966935e-05
prediction result:  [[11.024603]]
