In [54]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
from sklearn.model_selection import train_test_split

# 데이터

In [55]:
data = np.array(range(1, 101)) 
pre_data = np.array(range(96, 106))  
timesteps = 5

def split_x(dataset, timesteps):
    tmp = []
    for i in range(len(dataset) - timesteps + 1):  
        subset = dataset[i : (i + timesteps)]
        tmp.append(subset)
    return np.array(tmp)

data = split_x(data, timesteps) 
pre_data = split_x(pre_data, timesteps)

print("dataset.shape :", data.shape)
print("pre_data.shape: ", pre_data.shape)

data_x = data[:, :-1] 
data_y = data[:, -1]

pre_data = pre_data[:, :-1]
print("slicing_pre_data.shape : ", pre_data.shape)
print("slicing_pre_data:\n", pre_data)

print("data_x.shape: ", data_x.shape, "data_y.shape: ", data_y.shape)

x_train, x_test, y_train, y_test = train_test_split(data_x, data_y, train_size=0.7, random_state=3333) # default train_size = 0.75

print(x_train.shape, y_train.shape, x_test.shape, y_test.shape)

dataset.shape : (96, 5)
pre_data.shape:  (6, 5)
slicing_pre_data.shape :  (6, 4)
slicing_pre_data:
 [[ 96  97  98  99]
 [ 97  98  99 100]
 [ 98  99 100 101]
 [ 99 100 101 102]
 [100 101 102 103]
 [101 102 103 104]]
x.shape:  (96, 4) y.shape:  (96,)
(67, 4) (67,) (29, 4) (29,)


In [58]:
model = Sequential()                                                                     
model.add(Dense(units = 64, input_shape=(4,), activation='relu')) 
model.add(Dense(64, activation = 'relu'))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(64))
model.add(Dense(1))
model.summary() 

# LSTM을 두 개의 layer에서 사용할 때에는 return_sequences 파라미터를 지정해야한다. (default = False)


Model: "sequential_12"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_40 (Dense)            (None, 64)                320       
                                                                 
 dense_41 (Dense)            (None, 64)                4160      
                                                                 
 dense_42 (Dense)            (None, 64)                4160      
                                                                 
 dense_43 (Dense)            (None, 64)                4160      
                                                                 
 dense_44 (Dense)            (None, 1)                 65        
                                                                 
Total params: 12,865
Trainable params: 12,865
Non-trainable params: 0
_________________________________________________________________


# 컴파일, 훈련

In [57]:
model.compile(loss='mse', optimizer= 'adam')
model.fit(x_train, y_train, epochs=128, batch_size=3)

Epoch 1/128


ValueError: in user code:

    File "c:\Users\bitcamp\anaconda3\envs\tf27\lib\site-packages\keras\engine\training.py", line 878, in train_function  *
        return step_function(self, iterator)
    File "c:\Users\bitcamp\anaconda3\envs\tf27\lib\site-packages\keras\engine\training.py", line 867, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\bitcamp\anaconda3\envs\tf27\lib\site-packages\keras\engine\training.py", line 860, in run_step  **
        outputs = model.train_step(data)
    File "c:\Users\bitcamp\anaconda3\envs\tf27\lib\site-packages\keras\engine\training.py", line 808, in train_step
        y_pred = self(x, training=True)
    File "c:\Users\bitcamp\anaconda3\envs\tf27\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "c:\Users\bitcamp\anaconda3\envs\tf27\lib\site-packages\keras\engine\input_spec.py", line 263, in assert_input_compatibility
        raise ValueError(f'Input {input_index} of layer "{layer_name}" is '

    ValueError: Input 0 of layer "sequential_11" is incompatible with the layer: expected shape=(None, 2), found shape=(None, 4)


# 평가, 예측

In [ ]:
loss = model.evaluate(x_test, y_test)
print("loss: ", loss)

y_predict = np.array(pre_data)

result = model.predict(y_predict)

print('prediction result:\n', result)

1/1 [==============================] - 0s 63ms/step - loss: 1.3952e-04
loss:  0.0001395218714606017
prediction result:
 [[100.0171 ]
 [101.01726]
 [102.01741]
 [103.01757]
 [104.01772]
 [105.01788]]
